name: squash_archiver
description: Squash Archiver

publish_to: 'none'
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.1+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  # flutter_launcher_icons: ^0.7.5

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0

  # Service locator
  get_it: ^4.0.2
  injectable: ^0.4.0+1

  # data channel
  data_channel: ^1.0.4

  #url
  url_launcher: ^5.4.10

  # Local cache
  shared_preferences: ^0.5.7+1

  # annotations
  meta: ^1.1.8

  # API fetching
  dio: ^3.0.9

  # Connectivity
  data_connection_checker: ^0.3.4

  # Logging
  logger: ^0.9.1
  pretty_dio_logger: ^1.1.1
  sentry: ^3.0.1

  # Routing
  auto_route: ^0.5.0

  # Json
  json_annotation: ^3.0.1

  after_layout: ^1.0.7+2

  equatable: ^1.1.1

  #firebase
  firebase_messaging: ^6.0.13
  firebase_crashlytics: ^0.1.3+3

  # validator
  rules: ^1.0.2

  # back button handling
  back_button_interceptor: ^4.2.3

  #device info
  device_info: ^0.4.2+3
  package_info: ^0.4.1

  # loading
  cached_network_image: ^2.2.0+1

  ### widgets
  # snackbar
  flushbar: ^1.10.0

  # svg
  flutter_svg: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  lint: ^1.1.1

  # Build runner
  build_runner: ^1.9.0

  # Service locator
  injectable_generator: ^0.4.1

  # MobX
  mobx_codegen: ^1.0.3

  # Routing
  auto_route_generator: ^0.5.0

  # Json
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
