const FileTypeInfo = {
  'txt': 'Text Document',
  'csv': 'Comma-Separated Values File',
  'json': 'JSON File',
  'xml': 'XML File',
  'yaml': 'YAML File',
  'yml': 'YAML File',
  'doc': 'Microsoft Word Document',
  'docx': 'Microsoft Word Document',
  'xls': 'Microsoft Excel Spreadsheet',
  'xlsx': 'Microsoft Excel Spreadsheet',
  'ppt': 'Microsoft PowerPoint Presentation',
  'pptx': 'Microsoft PowerPoint Presentation',
  'pdf': 'PDF Document',
  'jpg': 'JPEG Image',
  'jpeg': 'JPEG Image',
  'png': 'PNG Image',
  'gif': 'GIF Image',
  'bmp': 'BMP Image',
  'mp3': 'MP3 Audio',
  'wav': 'WAV Audio',
  'mp4': 'MP4 Video',
  'avi': 'AVI Video',
  'mkv': 'MKV Video',
  'zip': 'ZIP Archive',
  'rar': 'RAR Archive',
  'tar': 'Tar Archive',
  'gz': 'Gzip Archive',
  '7z': '7-Zip Archive',
  'exe': 'Executable File',
  'dll': 'Dynamic Link Library',
  'tar.br': 'Brotli Compressed Tar Archive',
  'tar.bz2': 'Bzip2 Compressed Tar Archive',
  'tar.gz': 'Gzip Compressed Tar Archive',
  'tar.lz4': 'LZ4 Compressed Tar Archive',
  'tar.sz': 'Lzip Compressed Tar Archive',
  'tar.xz': 'xz Compressed Tar Archive',
  'tar.zst': 'Zstandard Compressed Tar Archive',
  'py': 'Python Script',
  'java': 'Java Source Code',
  'cpp': 'C++ Source Code',
  'html': 'HTML File',
  'css': 'CSS File',
  'js': 'JavaScript File',
  'php': 'PHP File',
  'sql': 'SQL File',
  'log': 'Log File',
  'cfg': 'Configuration File',
  'ini': 'INI File',
  'conf': 'Configuration File',
  'bak': 'Backup File',
  'tmp': 'Temporary File',
  'iso': 'Disc Image File',
  'bin': 'Binary Data File',
  'obj': 'Wavefront 3D Object File',
  'class': 'Java Class File',
  'jar': 'Java Archive',
  'war': 'Web Archive',
  'ear': 'Enterprise Archive',
  'deb': 'Debian Software Package',
  'rpm': 'Red Hat Package Manager File',
  'apk': 'Android Package File',
  'pptm': 'Microsoft PowerPoint Macro-Enabled Presentation',
  'pot': 'Microsoft PowerPoint Template',
  'potx': 'Microsoft PowerPoint Template',
  'potm': 'Microsoft PowerPoint Macro-Enabled Template',
  'ppa': 'Microsoft PowerPoint Add-in',
  'pps': 'Microsoft PowerPoint Slide Show',
  'ppsx': 'Microsoft PowerPoint Slide Show',
  'ppsm': 'Microsoft PowerPoint Macro-Enabled Slide Show',
  'rtf': 'Rich Text Format',
  'odt': 'OpenDocument Text',
  'ods': 'OpenDocument Spreadsheet',
  'odp': 'OpenDocument Presentation',
  'odg': 'OpenDocument Graphics',
  'odc': 'OpenDocument Chart',
  'odb': 'OpenDocument Database',
  'odf': 'OpenDocument Formula',
  'srt': 'SubRip Subtitle File',
  'sub': 'SubStation Alpha Subtitle File',
  'ass': 'Advanced SubStation Alpha Subtitle File',
  'ssa': 'SubStation Alpha Subtitle File',
  'idx': 'Subtitle Index File',
  'img': 'Disk Image',
  'dmg': 'Mac OS X Disk Image',
  'cue': 'Cue Sheet File',
  'sh': 'Shell Script',
  'bat': 'Batch File',
  'ps1': 'PowerShell Script',
  'com': 'Command File',
  'cmd': 'Windows Command Script',
  'vbs': 'VBScript File',
  'reg': 'Registry File',
  'inf': 'Setup Information File',
  'url': 'Internet Shortcut',
  'desktop': 'Desktop Entry File',
  'docm': 'Microsoft Word Macro-Enabled Document',
  'dot': 'Microsoft Word Document Template',
  'dotx': 'Microsoft Word Document Template',
  'dotm': 'Microsoft Word Macro-Enabled Document Template',
  'xlt': 'Microsoft Excel Template',
  'xltx': 'Microsoft Excel Template',
  'xltm': 'Microsoft Excel Macro-Enabled Template',
  'xlsb': 'Microsoft Excel Binary Spreadsheet',
  'xlam': 'Microsoft Excel Add-in',
  'ics': 'iCalendar File',
  'vcf': 'vCard File',
  'm4a': 'MPEG-4 Audio Layer',
  'flac': 'Free Lossless Audio Codec File',
  'aac': 'Advanced Audio Codec File',
  'wma': 'Windows Media Audio File',
  'ogg': 'Ogg Vorbis Audio File',
  'tiff': 'Tagged Image File Format',
  'webp': 'WebP Image',
  'raw': 'Camera Raw Image',
  'ico': 'Icon Image File',
  'svg': 'Scalable Vector Graphics File',
  'ai': 'Adobe Illustrator File',
  'eps': 'Encapsulated PostScript File',
  'psd': 'Adobe Photoshop Document',
  'indd': 'Adobe InDesign Document',
  'mpg': 'MPEG Video File',
  'mpeg': 'MPEG Video File',
  'mov': 'QuickTime Movie',
  'wmv': 'Windows Media Video File',
  'flv': 'Flash Video File',
  'vob': 'DVD Video Object File',
  'asf': 'Advanced Systems Format File',
  'm3u': 'M3U Playlist File',
  'pls': 'PLS Playlist File',
  'jsx': 'JavaScript JSX File',
  'coffee': 'CoffeeScript File',
  'ts': 'TypeScript File',
  'dart': 'Dart Source Code File',
  'go': 'Go Source Code File',
  'rs': 'Rust Source Code File',
  'cs': 'C# Source Code File',
  'vb': 'Visual Basic File',
  'lua': 'Lua Script',
  'pl': 'Perl Script',
  'pyc': 'Python Compiled File',
  'pyp': 'Python Pickle File',
  'pyo': 'Python Optimized Code File',
  'pyd': 'Python Dynamic Module',
  'whl': 'Python Wheel Package',
  'pyz': 'Python Archive',
  'ipa': 'iOS App Archive',
  'cab': 'Windows Cabinet File',
  'so': 'Shared Object File',
  'lib': 'Library File',
  'a': 'Static Library File',
  'dylib': 'Dynamic Library',
  'swf': 'Shockwave Flash Movie',
  'vdi': 'VirtualBox Virtual Disk Image',
  'vmdk': 'VMware Virtual Disk File',
  'vbox': 'VirtualBox Settings File',
  'vbox-extpack': 'VirtualBox Extension Pack',
  'msi': 'Windows Installer Package',
  'msp': 'Windows Installer Patch',
  'toast': 'Toast Disk Image',
  'vcd': 'Virtual CD',
  'hfs': 'HFS Disk Image',
  'sparseimage': 'macOS Sparse Image',
  'app': 'macOS Application',
  'pkg': 'macOS Installer Package',
  'nrg': 'Nero CD/DVD Image File',
  'dmgpart': 'macOS Disk Image Part',
  'xpi': 'Mozilla Firefox Add-on',
  'crx': 'Google Chrome Extension',
  'eml': 'Email Message',
  'msg': 'Outlook Mail Message',
  'pst': 'Outlook Personal Information Store File',
  'ost': 'Outlook Offline Data File',
  'mbox': 'Mailbox File',
  'vcs': 'vCalendar File',
  'evt': 'Windows Event Log File',
  'md': 'Markdown Document',
  'bashrc': 'Bashrc File',
  'vimrc': 'Vim Configuration File',
  'rb': 'Ruby Script',
  'db': 'Database File',
  'mdb': 'Microsoft Access Database',
  'accdb': 'Microsoft Access Database (2007 or newer)',
  'sqlitedb': 'SQLite Database',
  'tgz': 'Tar Gzip Compressed File',
  'bz2': 'Bzip2 Compressed File',
  'xz': 'XZ Compressed File',
  'arj': 'ARJ Compressed File',
  'z': 'Z Compressed File',
  'mdf': 'SQL Server Database File',
  'dsk': 'Disk Image',
  'hdd': 'Hard Disk Image',
  'vhd': 'Virtual Hard Disk',
  'vhdx': 'Windows Hyper-V Virtual Hard Disk',
  'wim': 'Windows Imaging Format',
  'xcf': 'GIMP Image File',
  'dwg': 'AutoCAD Drawing Database File',
  'dxf': 'AutoCAD Drawing Exchange Format File',
  '3ds': '3D Studio Scene File',
  'max': '3ds Max Scene File',
  'blend': 'Blender 3D Data File',
  'stl': 'Stereolithography File',
  'fbx': 'Autodesk FBX Interchange File',
  'mid': 'MIDI File',
  'midi': 'MIDI File',
  'amr': 'Adaptive Multi-Rate Codec File',
  'webm': 'WebM Video File',
  'm4v': 'iTunes Video File',
  '3gp': '3GPP Multimedia File',
  'ogv': 'Ogg Video File',
  'mxf': 'Material Exchange Format File',
  'emf': 'Enhanced Metafile',
  'ps': 'PostScript File',
  'djvu': 'DjVu Document',
  'epub': 'EPUB File',
};
